import os
import pathlib
from typing import Optional, TYPE_CHECKING

from bes_rules import DATA_PATH
from bes_rules.utils.modelica import load_modelica_file_modifier
from bes_rules.configs.inputs.base import BaseInputConfig

if TYPE_CHECKING:
    from bes_rules.configs import InputConfig


class UserProfile(BaseInputConfig):
    """
    Config to define user profiles.

    Args:
        internal_gains_path (pathlib.Path): If not given, the TEASER output is used, generated by the building config. If provided, should be a teaser-format internal gains file
        use_stochastic_internal_gains (bool):
            If True, stochastic electricity profiles are loaded based on
            the number of occupants from the data directory.
        with_persons (bool):
            If False, internal gains from persons is disabled
        with_electrical_gains (bool):
            If False, internal gains from electrical appliances and light is disabled.
    """
    room_set_temperature: float = 293.15
    night_set_back: int = 0
    internal_gains_path: Optional[pathlib.Path] = None
    use_stochastic_internal_gains: bool = False
    with_persons: bool = True
    with_electrical_gains: bool = True
    custom_model: Optional[str] = None
    custom_model_hom: Optional[str] = None

    def get_modelica_modifier(self, input_config: "InputConfig"):
        if input_config.hom:
            return ""

        if self.with_electrical_gains and self.with_persons:
            gains_modifier = "gain={1,1,1}"
        elif self.with_persons:
            gains_modifier = "gain={1,0,0}"
        elif self.with_electrical_gains:
            gains_modifier = "gain={0,1,1}"
        else:
            gains_modifier = "gain={0,0,0}"
        room_set_temperature_modifier = (
            f'systemParameters(\n'
            f'  TSetZone_nominal=fill({self.room_set_temperature}, 1)'
            f')'
        )
        if not self.use_stochastic_internal_gains:
            return (
                f'userProfiles(dTSetBack={self.night_set_back},{gains_modifier}),\n'
                f'{room_set_temperature_modifier}'
            )
        if self.internal_gains_path is None:
            internal_gains_path = input_config.building.get_internal_gains_from_teaser()
        else:
            internal_gains_path = self.internal_gains_path
        _path_modifier = f"fileNameIntGains={load_modelica_file_modifier(internal_gains_path)}"
        electricity_path = self.get_electricity_path(input_config.building.number_of_occupants)
        if not os.path.exists(electricity_path):
            raise ValueError(
                f"Given number of occupants has no electricity profile. "
                f"Generate it first and add it to {electricity_path.parent}"
            )
        modifier = f'fileNameElePro={load_modelica_file_modifier(electricity_path)}'
        return (
            f'userProfiles('
            f'use_absIntGai=true,'
            f'{_path_modifier},\n'
            'gain={1,0,0},\n'
            f'{modifier},\n'
            f'dTSetBack={self.night_set_back}),'
            f'{room_set_temperature_modifier}'
        )

    @staticmethod
    def get_electricity_path(number_of_occupants: int):
        return DATA_PATH.joinpath(
            "electricity_profiles",
            f"{number_of_occupants}_occupants.txt"
        )

    def get_name(self):
        if self.custom_model is not None:
            extra_ = self.custom_model.split(".")[-1].replace("MonovalentVitoCal_HOM_", "")
        else:
            extra_ = ''
        def _get_no_str(b: bool):
            return '' if b else 'No'

        def _get_if_not_20degC(v):
            return '' if v == 293.15 else str(round(v - 273.15))

        return (f"{self.night_set_back}K-"
                f"{_get_no_str(self.with_persons)}Per-"
                f"{_get_no_str(self.with_electrical_gains)}IntGai"
                f"{_get_if_not_20degC(self.room_set_temperature)}"
                f"{extra_}")
